[WPDS-1093, WPDS-1023, WPDS-1024] Feat: create dive deeper feed
washingtonpost/wpds-v0-docs pull request #111
Opened 2022-07-12 21:19 UTC by atomictangerine

Adds Dive Deeper section to the main page. Expands on @clairehhelms ' guide ranking system + grids.
Based on internal Jira Ticket WPDS-1093, WPDS-1023, WPDS-1024.

<img width="1840" alt="Screen Shot 2022-07-12 at 5 00 18 PM" src="https://user-images.githubusercontent.com/7713464/178597154-a69ffe6e-b49f-475f-8032-4214a3e6b6c3.png">
<img width="457" alt="Screen Shot 2022-07-12 at 5 00 10 PM" src="https://user-images.githubusercontent.com/7713464/178597158-aa79534e-379b-467b-aace-3f15932b6233.png">
<img width="455" alt="Screen Shot 2022-07-12 at 5 00 04 PM" src="https://user-images.githubusercontent.com/7713464/178597160-cfb4b3cd-14b0-4432-887d-c4e30cccd199.png">
<img width="1840" alt="Screen Shot 2022-07-12 at 4 59 48 PM" src="https://user-images.githubusercontent.com/7713464/178597161-22017ad4-309d-46d0-86c6-7524871d7ee6.png">
<img width="1840" alt="Screen Shot 2022-07-12 at 4 59 43 PM" src="https://user-images.githubusercontent.com/7713464/178597163-b4e59144-e8cb-4d03-bcc9-ec0abebad1c6.png">
<img width="1840" alt="Screen Shot 2022-07-12 at 4 59 35 PM" src="https://user-images.githubusercontent.com/7713464/178597165-e9b41cdc-2713-4b01-a865-dbe826c43421.png">
<img width="1840" alt="Screen Shot 2022-07-12 at 4 59 30 PM" src="https://user-images.githubusercontent.com/7713464/178597166-4c54044e-f5e9-47e1-8f94-a24eb6bfc062.png">

// Will squash to use conventional commits

2022-07-13 01:17 UTC, artmsilva commented on components/Markdown/Components/link.js
> +    <Link as={as} href={href} forceHref passHref>
💯

2022-07-13 01:18 UTC, artmsilva commented on pages/index.js
> +      <LandingContentGrid size={"wide"}>
```suggestion
      <LandingContentGrid size="wide">
```
⛏️

2022-07-13 01:18 UTC, artmsilva commented on pages/index.js
> +                "@sm": { paddingBottom: "0", marginBottom: 0 },
⛏️ 
```suggestion
                "@sm": { paddingBottom: 0, marginBottom: 0 },
```

2022-07-13 01:20 UTC, artmsilva commented on pages/utils.js
> +import { Header } from "~/components/Markdown/Components/headers";
This created a new route/page in our app. https://wpds-docs-git-feat-create-dive-deeper-feed.preview.now.washingtonpost.com/utils. You could place these utils in a new folder in /components.

2022-07-13 01:21 UTC, artmsilva commented on public/sitemap.xml
> +    <loc>https://build.washingtonpost.com/utils</loc>
See above comment. https://wpds-docs-git-feat-create-dive-deeper-feed.preview.now.washingtonpost.com/utils

2022-07-13 01:21 UTC, artmsilva requested changes
I left some notes. Let's look into moving the utils.js file into components directory.

2022-07-13 19:16 UTC, clairehhelms commented on docs/resources/workshops/developer_4-7-22.mdx
> +imageAltText: To the right of the image, a man stands holding a text box with both hands. In front of him a large website floats in front of him. He appears to be inserting the text box into the uppe
I like the alt text!

2022-07-13 19:18 UTC, clairehhelms commented on pages/resources/index.js
> +    return { name, posts, description, size, type, id };
thank you for cleaning these up!! <3

2022-07-13 19:21 UTC, clairehhelms approved these changes

2022-07-14 16:08 UTC, artmsilva approved these changes

2022-07-18 16:03 UTC, merged