fix: nitpicks/add some details for theme tokens
washingtonpost/wpds-v0-docs pull request #41
Opened 2022-03-03 21:21 UTC by nhidtran

2022-03-03 21:40 UTC, BrianAA requested changes
Just small spacing refinements and placement

2022-03-03 21:40 UTC, BrianAA commented on docs/foundations/shadow.mdx
add a `<br/>` for spacing

2022-03-03 21:40 UTC, BrianAA commented on docs/foundations/color.mdx
> +When using color tokens in code, you can access them using `theme.colors.[tokenName]`
Move this below to the Theme and Semantic section Line 22

2022-03-03 21:40 UTC, BrianAA commented on docs/foundations/size.mdx
> +When using size tokens in code, you can access them using `theme.size.[tokenName]`
add a `<BR/>` for spacing

2022-03-07 20:10 UTC, artmsilva approved these changes

2022-03-07 20:11 UTC, artmsilva commented
@nhidtran Great job!! Thank you for contributing to our docs.<img src="https://media2.giphy.com/media/R6gvnAxj2ISzJdbA63/giphy-downsized-medium.gif"/>

2022-03-07 20:19 UTC, merged