Stitches doc
washingtonpost/wpds-v0-docs pull request #98
Opened 2022-06-15 20:25 UTC by clairehhelms

short documentation about using some stitches functionality for ui kit users. Please check for info that I may have missed or is confusing!

2022-06-17 00:41 UTC, artmsilva approved these changes

2022-06-21 16:15 UTC, clairehhelms commented
// go to resources -> using stitches to style your products :-)

2022-06-22 21:09 UTC, atomictangerine requested changes
Looks good! I would suggest not using words like `here` to link out to other pages, but instead use something more descriptive that lets people know where they're going.
That being said, I LOVE THE EXAMPLES. Great job. Super easy to follow and so much easier to understand that the actual stitches docs.

2022-06-22 21:09 UTC, atomictangerine commented on docs/resources/architecture/themes.mdx
> +Another function available in Stitches is the `keyframes` function. Using the keyframe animation technique, Stitches allows the creation of global CSS keyframe rules, which let transitions be easily
nit: which `lets` transitions...

2022-06-22 21:09 UTC, atomictangerine commented on docs/resources/architecture/themes.mdx
> +Stitches is also capable of defining breakpoints, which are reusable media queries useful for responsive styling. The WPDS UI Kit supports a variety of size breakpoints and custom themes, which can b
Personally, I'm not a big fan of having the word `here` be a link out. Perhaps you could say 'which can be explored in the [stitches.config.ts](https://github.com/washingtonpost/wpds-ui-kit/blob/main/ui/theme/src/stitches.config.ts)' or something like that

2022-06-23 14:24 UTC, artmsilva approved these changes

2022-06-23 20:38 UTC, clairehhelms commented
Will merge upon updating with styling based on parent element tags (eg for dark mode)

2022-06-23 21:00 UTC, atomictangerine approved these changes

2022-06-28 15:53 UTC, merged